
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='an2linuxserver',
    description='Sync Android notifications encrypted to a Linux desktop',
    version_format='{tag}.dev{commitcount}+{gitsha}',
    setup_requires=['setuptools-git-version'],
    url='https://github.com/rootkiwi/an2linuxserver',
    packages=[],
    package_dir={"": "."},
    package_data={},
    install_requires=['pygobject'],
)
